### ISSUE TITLE
关于腾讯字体

### ISSUE THREAD

**Issue by whale2002** [Gsgzs/com.tencent.www#1]
腾讯字体文件您是从哪儿找到的呢

**Comment by ydsuper** [comment]
sorry~ 现在才看到。请参考下面的示例~
![image](https://user-images.githubusercontent.com/55370794/123537566-a6caaf80-d762-11eb-89d6-547a87141b86.png)

**Comment by ydsuper** [comment]
The issue has been resolved. 
Welcome to issue at any time~
